# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install more recent versions of some OS X tools
tap homebrew/dupes
install homebrew/dupes/grep

# Install other useful binaries
install grep
install wget
install git
install tree
install webkit2png

# Storage
install mongodb
install redis

# Speedtest CLI
install speedtest_cli

# Remove outdated versions from the cellar
cleanup