# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install more recent versions of some OS X tools
tap homebrew/dupes
install homebrew/dupes/grep

# bash-completion
install bash-completion

# Install other useful binaries
install grep
install wget
install git
install tree
install webkit2png

# FFMPEG
install ffmpeg

# Storage
install mongodb
install redis
install postgresql

# Speedtest CLI
install speedtest_cli

# Git Extras - https://github.com/visionmedia/git-extras
install git-extras

# terminal-notifier - replacing growlnotify
install terminal-notifier

# Remove outdated versions from the cellar
cleanup